x-app-defaults: &app-defaults
  env_file:
    - ../../.env
  networks:
    - internal

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-worker
    <<: *app-defaults
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_worker:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-worker
    ports:
      - "5672:5672"
      - "15672:15672"
    <<: *app-defaults
    volumes:
      - rabbitmq_data_worker:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: minio-worker
    ports:
      - "9000:9000"
      - "9001:9001"
    <<: *app-defaults
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_worker:/data

volumes:
  postgres_data_worker:
  rabbitmq_data_worker:
  minio_data_worker:

networks:
  internal:
    driver: bridge
