version: "3.9"

services:
  api:
    image: localhost:5000/health-vitals-api:dev

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.health-vitals-api.rule=Host(`api.binderlex.com`)"
        - "traefik.http.routers.health-vitals-api.entrypoints=websecure"
        - "traefik.http.routers.health-vitals-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.health-vitals-api.loadbalancer.server.port=3000"
    env_file:
      - ../.env.local
    networks:
      - prod01

  worker:
    image: localhost:5000/health-vitals-worker:dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ../.env.local
    networks:
      - prod01

networks:
  prod01:
    external: true
