version: "3.9"

services:
  traefik:
    image: traefik:v3.4.0
    command:
      - "--providers.swarm=true"
      - "--providers.docker.network=prod01"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "8080:8080" # dashboard
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - prod01
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  prod01:
    external: true
